version: '3'
services:
    db: 
        image: postgres:latest
        container_name: postgre-container
        ports: 
            - 5432:5432
        volumes:
            - ./pg_data:/var/lib/postgresql/data/pgdata
        environment:
           POSTGRES_PASSWORD: pass
           POSTGRES_DB: test_db
           PGDATA: /var/lib/postgresql/data/pgdata
        restart: always
    app:
        image: simple-app-rest:v1
        container_name: app-db
        ports:
            - 8081:8080
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test_db
            - SPRING_DATASOURCE_USERNAME=userone
            - SPRING_DATASOURCE_PASSWORD=pass
        restart: always
        links:
            - db        
        